apiVersion: v1
kind: LimitRange
metadata:             # <--- FIXED: Must be lowercase 'm'
  name: pod-limit
  namespace: xgoods
spec:
  limits:
    - type: Container
      max:  
        cpu: "500m"
        memory: "512Mi"
      min:
        cpu: "50m"
        memory: "64Mi"
      default:
        cpu: "150m"
        memory: "128Mi"
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"