apiVersion: v1
kind: Service
metadata:
  name: podservice
  namespace: xgoods
spec:
  selector:
    app: myapp
    type: frontend
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80 #service port
---