apiVersion: v1
kind: Pod             
metadata:            
  name: myapp-pod
  namespace: xgoods   
  labels:
    app: myapp
    type: frontend
spec:
  containers:
    - name: frontend-container
      image: nginx