apiVersion: v1
kind: Pod             
metadata:             # FIXED: Correct spelling (was 'metadta')
  name: myapp-pod
  namespace: xgoods   # Best practice: Put namespace inside the file
  labels:
    app: myapp
    type: frontend
spec:
  containers:
    - name: frontend-container
      image: nginx