apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-quota
  namespace: xgoods
spec:
  hard:
    pods: "10"
    requests.cpu: "1" 
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "1.5gi"