apiVersion: v1
kind: Pod             
metadata:
  name: xgoods-pod-reourcesandlimits
  namespace: xgoods
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "68Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"